language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm
    - 
jobs:
  include:
    - php: '7.2'
    - php: '7.3'
    - php: '7.3'
      env: COVERAGE=yes
  allow_failures:
    - env: COVERAGE=yes
  fast_finish: true

before_install:
  - if [[ $COVERAGE != yes ]]; then phpenv config-rm xdebug.ini || echo "xdebug not available"; fi;
  - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - composer install --prefer-dist --no-progress --no-suggest --ansi

script:
  - ./console doctrine:database:create --env=test
  - ./console doctrine:schema:update --force --env=test
  - 'if [[ $COVERAGE = yes ]]; then
        ./vendor/bin/behat -f progress -p coverage;
        ./vendor/bin/phpunit --coverage-php=build/cov/coverage-php.cov;
    else
        ./vendor/bin/behat -f progress;
        ./vendor/bin/phpunit;
    fi'

after_script:
  # process coverage
  - 'if [[ $COVERAGE = yes ]]; then
        mkdir -p build/logs;
        wget https://phar.phpunit.de/phpcov.phar;
        php phpcov.phar merge --clover build/logs/clover.xml build/cov;
        composer require php-coveralls/php-coveralls --no-scripts;
        travis_retry vendor/bin/php-coveralls -vvv;
        wget https://scrutinizer-ci.com/ocular.phar;
        travis_retry php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml;
    fi'