<?php

/*
 * This file is part of the DoyoUserBundle project.
 *
 * (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (class_exists(\Container7SeNx6A\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7SeNx6A/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container7SeNx6A.legacy');

    return;
}

if (!class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    class_alias(\Container7SeNx6A\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \Container7SeNx6A\srcApp_KernelTestDebugContainer([
    'container.build_hash' => '7SeNx6A',
    'container.build_id'   => '861d9d4a',
    'container.build_time' => 1556871115,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7SeNx6A');
