<?php

/*
 * This file is part of the DoyoUserBundle project.
 *
 * (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (class_exists(\ContainerEf3OHFH\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEf3OHFH/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEf3OHFH.legacy');

    return;
}

if (!class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    class_alias(\ContainerEf3OHFH\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerEf3OHFH\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ef3OHFH',
    'container.build_id'   => 'c150f9ba',
    'container.build_time' => 1556877847,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEf3OHFH');
