<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'vue' => [
            'js' => [
                'http://localhost:8080/build/runtime.js',
                'http://localhost:8080/build/vendors~vue.js',
                'http://localhost:8080/build/vue.js',
            ],
            'css' => [
                'http://localhost:8080/build/vendors~vue.css',
                'http://localhost:8080/build/vue.css',
            ],
        ],
    ],
],

]];
