<?php

/*
 * This file is part of the DoyoUserBundle project.
 *
 * (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.KTVqfp6' shared service.

return $this->privates['.service_locator.KTVqfp6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'doctrine'                       => ['services', 'doctrine', 'getDoctrineService', false],
    'http_kernel'                    => ['services', 'http_kernel', 'getHttpKernelService', false],
    'parameter_bag'                  => ['privates', 'parameter_bag', 'getParameterBagService', false],
    'request_stack'                  => ['services', 'request_stack', 'getRequestStackService', false],
    'router'                         => ['services', 'router', 'getRouterService', false],
    'security.authorization_checker' => ['services', 'security.authorization_checker', 'getSecurity_AuthorizationCheckerService', false],
    'security.csrf.token_manager'    => ['services', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService.php', true],
    'security.token_storage'         => ['services', 'security.token_storage', 'getSecurity_TokenStorageService', false],
    'serializer'                     => ['services', 'serializer', 'getSerializerService', false],
    'session'                        => ['services', 'session', 'getSessionService.php', true],
    'twig'                           => ['services', 'twig', 'getTwigService', false],
]);
