<?php

/*
 * This file is part of the DoyoUserBundle project.
 *
 * (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_platform.pagination' shared service.

include_once $this->targetDirs[4].'/vendor/api-platform/core/src/DataProvider/Pagination.php';

return $this->privates['api_platform.pagination'] = new \ApiPlatform\Core\DataProvider\Pagination(($this->privates['api_platform.metadata.resource.metadata_factory.cached'] ?? $this->getApiPlatform_Metadata_Resource_MetadataFactory_CachedService()), $this->parameters['api_platform.collection.pagination']);
