<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doyo_user.listeners.user' shared autowired service.

include_once $this->targetDirs[4].'/vendor/doctrine/event-manager/lib/Doctrine/Common/EventSubscriber.php';
include_once $this->targetDirs[4].'/src/Listener/UserListener.php';

return $this->privates['doyo_user.listeners.user'] = new \Doyo\UserBundle\Listener\UserListener(($this->privates['doyo_user.util.password_updater'] ?? $this->load('getDoyoUser_Util_PasswordUpdaterService.php')));
