<?php

/*
 * This file is part of the DoyoUserBundle project.
 *
 * (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doyo_user.util.password_updater' shared autowired service.

include_once $this->targetDirs[4].'/src/Util/PasswordUpdaterInterface.php';
include_once $this->targetDirs[4].'/src/Util/PasswordUpdater.php';

return $this->privates['doyo_user.util.password_updater'] = new \Doyo\UserBundle\Util\PasswordUpdater(($this->privates['security.encoder_factory.generic'] ?? $this->load('getSecurity_EncoderFactory_GenericService.php')));
