<?php

/*
 * This file is part of the DoyoUserBundle project.
 *
 * (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doyo_user.service.mailer' shared autowired service.

include_once $this->targetDirs[4].'/src/Mailer/MailerInterface.php';
include_once $this->targetDirs[4].'/src/Mailer/Mailer.php';

return $this->privates['doyo_user.service.mailer'] = new \Doyo\UserBundle\Mailer\Mailer(($this->services['swiftmailer.mailer.default'] ?? $this->load('getSwiftmailer_Mailer_DefaultService.php')), ($this->services['router'] ?? $this->getRouterService()), ($this->services['translator'] ?? $this->getTranslatorService()), 'app_reset_password_confirm', 'app_register_confirm');
