<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doyo_user.util.password_updater' shared autowired service.

include_once $this->targetDirs[4].'/src/Util/PasswordUpdaterInterface.php';
include_once $this->targetDirs[4].'/src/Util/PasswordUpdater.php';

return $this->privates['doyo_user.util.password_updater'] = new \Doyo\UserBundle\Util\PasswordUpdater(($this->privates['security.encoder_factory.generic'] ?? $this->load('getSecurity_EncoderFactory_GenericService.php')));
