<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Doyo\UserBundle\Controller\ProfileController' shared autowired service.

include_once $this->targetDirs[4].'/vendor/symfony/framework-bundle/Controller/ControllerTrait.php';
include_once $this->targetDirs[4].'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
include_once $this->targetDirs[4].'/src/Controller/ProfileController.php';

$this->services['Doyo\\UserBundle\\Controller\\ProfileController'] = $instance = new \Doyo\UserBundle\Controller\ProfileController();

$instance->setContainer(($this->privates['.service_locator.KTVqfp6'] ?? $this->load('get_ServiceLocator_KTVqfp6Service.php'))->withContext('Doyo\\UserBundle\\Controller\\ProfileController', $this));

return $instance;
