<?php

/*
 * This file is part of the DoyoUserBundle project.
 *
 * (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.failure_handler.main.json_login' shared service.

include_once $this->targetDirs[4].'/vendor/symfony/security-http/Authentication/AuthenticationFailureHandlerInterface.php';
include_once $this->targetDirs[4].'/vendor/symfony/security-http/Authentication/CustomAuthenticationFailureHandler.php';

return $this->privates['security.authentication.failure_handler.main.json_login'] = new \Symfony\Component\Security\Http\Authentication\CustomAuthenticationFailureHandler(($this->privates['lexik_jwt_authentication.handler.authentication_failure'] ?? $this->load('getLexikJwtAuthentication_Handler_AuthenticationFailureService.php')), []);
