<?php

/*
 * This file is part of the DoyoUserBundle project.
 *
 * (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.csrf.token_storage' shared service.

include_once $this->targetDirs[4].'/vendor/symfony/security-csrf/TokenStorage/TokenStorageInterface.php';
include_once $this->targetDirs[4].'/vendor/symfony/security-csrf/TokenStorage/ClearableTokenStorageInterface.php';
include_once $this->targetDirs[4].'/vendor/symfony/security-csrf/TokenStorage/SessionTokenStorage.php';

return $this->privates['security.csrf.token_storage'] = new \Symfony\Component\Security\Csrf\TokenStorage\SessionTokenStorage(($this->services['session'] ?? $this->load('getSessionService.php')));
