<?php

/*
 * This file is part of the DoyoUserBundle project.
 *
 * (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.firewall.map.config.main' shared service.

include_once $this->targetDirs[4].'/vendor/symfony/security-bundle/Security/FirewallConfig.php';

return $this->privates['security.firewall.map.config.main'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallConfig('main', 'security.user_checker', null, true, true, 'security.user.provider.concrete.app_user_provider', null, 'lexik_jwt_authentication.jwt_token_authenticator', null, null, [0 => 'guard', 1 => 'json_login', 2 => 'anonymous'], null);
