<?php

/*
 * This file is part of the DoyoUserBundle project.
 *
 * (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'session.attribute_bag' shared service.

include_once $this->targetDirs[4].'/vendor/symfony/http-foundation/Session/SessionBagInterface.php';
include_once $this->targetDirs[4].'/vendor/symfony/http-foundation/Session/Attribute/AttributeBagInterface.php';
include_once $this->targetDirs[4].'/vendor/symfony/http-foundation/Session/Attribute/AttributeBag.php';

return $this->privates['session.attribute_bag'] = new \Symfony\Component\HttpFoundation\Session\Attribute\AttributeBag();
