<?php

/*
 * This file is part of the DoyoUserBundle project.
 *
 * (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.orm.validator.unique' shared service.

include_once $this->targetDirs[4].'/vendor/symfony/validator/ConstraintValidatorInterface.php';
include_once $this->targetDirs[4].'/vendor/symfony/validator/ConstraintValidator.php';
include_once $this->targetDirs[4].'/vendor/symfony/doctrine-bridge/Validator/Constraints/UniqueEntityValidator.php';

return $this->privates['doctrine.orm.validator.unique'] = new \Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntityValidator(($this->services['doctrine'] ?? $this->getDoctrineService()));
