<?php

/*
 * This file is part of the DoyoUserBundle project.
 *
 * (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'lexik_jwt_authentication.jwt_manager' shared service.

include_once $this->targetDirs[4].'/vendor/lexik/jwt-authentication-bundle/Services/JWTManagerInterface.php';
include_once $this->targetDirs[4].'/vendor/lexik/jwt-authentication-bundle/Services/JWTTokenManagerInterface.php';
include_once $this->targetDirs[4].'/vendor/lexik/jwt-authentication-bundle/Services/JWTManager.php';

$this->services['lexik_jwt_authentication.jwt_manager'] = $instance = new \Lexik\Bundle\JWTAuthenticationBundle\Services\JWTManager(($this->services['lexik_jwt_authentication.encoder'] ?? $this->load('getLexikJwtAuthentication_EncoderService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), 'username');

$instance->setUserIdentityField('username');

return $instance;
