<?php

/*
 * This file is part of the DoyoUserBundle project.
 *
 * (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'translation.extractor' shared service.

include_once $this->targetDirs[4].'/vendor/symfony/translation/Extractor/ExtractorInterface.php';
include_once $this->targetDirs[4].'/vendor/symfony/translation/Extractor/ChainExtractor.php';
include_once $this->targetDirs[4].'/vendor/symfony/translation/Extractor/AbstractFileExtractor.php';
include_once $this->targetDirs[4].'/vendor/symfony/translation/Extractor/PhpExtractor.php';
include_once $this->targetDirs[4].'/vendor/symfony/twig-bridge/Translation/TwigExtractor.php';

$this->privates['translation.extractor'] = $instance = new \Symfony\Component\Translation\Extractor\ChainExtractor();

$instance->addExtractor('php', new \Symfony\Component\Translation\Extractor\PhpExtractor());
$instance->addExtractor('twig', new \Symfony\Bridge\Twig\Translation\TwigExtractor(($this->services['twig'] ?? $this->getTwigService())));

return $instance;
