<?php

/*
 * This file is part of the DoyoUserBundle project.
 *
 * (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.j.92UUt' shared service.

return $this->privates['.service_locator.j.92UUt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'Doyo\\UserBundle\\Controller\\ResetPasswordController::newPassword' => ['privates', '.service_locator.0uMCgxy', 'get_ServiceLocator_0uMCgxyService.php', true],
    'Doyo\\UserBundle\\Controller\\ResetPasswordController::request'     => ['privates', '.service_locator.0uMCgxy', 'get_ServiceLocator_0uMCgxyService.php', true],
    'Doyo\\UserBundle\\Controller\\ResetPasswordController:newPassword'  => ['privates', '.service_locator.0uMCgxy', 'get_ServiceLocator_0uMCgxyService.php', true],
    'Doyo\\UserBundle\\Controller\\ResetPasswordController:request'      => ['privates', '.service_locator.0uMCgxy', 'get_ServiceLocator_0uMCgxyService.php', true],
]);
