<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.0uMCgxy' shared service.

return $this->privates['.service_locator.0uMCgxy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'service' => ['privates', 'doyo_user.security.reset_password', 'getDoyoUser_Security_ResetPasswordService.php', true],
]);
