<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doyo_user.service.mailer' shared autowired service.

include_once $this->targetDirs[4].'/src/Mailer/MailerInterface.php';
include_once $this->targetDirs[4].'/src/Mailer/Mailer.php';

return $this->privates['doyo_user.service.mailer'] = new \Doyo\UserBundle\Mailer\Mailer(($this->services['swiftmailer.mailer.default'] ?? $this->load('getSwiftmailer_Mailer_DefaultService.php')), ($this->services['router'] ?? $this->getRouterService()), ($this->services['translator'] ?? $this->getTranslatorService()), 'app_reset_password_confirm', 'app_register_confirm');
