<?php

/*
 * This file is part of the DoyoUserBundle project.
 *
 * (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine.dbal.default_connection.configuration' shared service.

include_once $this->targetDirs[4].'/vendor/doctrine/dbal/lib/Doctrine/DBAL/Configuration.php';

$this->privates['doctrine.dbal.default_connection.configuration'] = $instance = new \Doctrine\DBAL\Configuration();

$instance->setSQLLogger(($this->privates['doctrine.dbal.logger.chain.default'] ?? $this->load('getDoctrine_Dbal_Logger_Chain_DefaultService.php')));

return $instance;
