<?php

/*
 * This file is part of the DoyoUserBundle project.
 *
 * (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doyo_user.service.user_manager' shared autowired service.

include_once $this->targetDirs[4].'/src/Manager/UserManagerInterface.php';
include_once $this->targetDirs[4].'/src/Manager/UserManager.php';

return $this->privates['doyo_user.service.user_manager'] = new \Doyo\UserBundle\Manager\UserManager(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')), 'App\\Entity\\User');
