<?php

/*
 * This file is part of the DoyoUserBundle project.
 *
 * (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doyo_user.providers.user_item' shared autowired service.

include_once $this->targetDirs[4].'/vendor/api-platform/core/src/DataProvider/RestrictedDataProviderInterface.php';
include_once $this->targetDirs[4].'/src/DataProvider/UserItemDataProvider.php';

return $this->privates['doyo_user.providers.user_item'] = new \Doyo\UserBundle\DataProvider\UserItemDataProvider(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')), 'App\\Entity\\User');
