<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doyo_user.providers.user_item' shared autowired service.

include_once $this->targetDirs[4].'/vendor/api-platform/core/src/DataProvider/RestrictedDataProviderInterface.php';
include_once $this->targetDirs[4].'/src/DataProvider/UserItemDataProvider.php';

return $this->privates['doyo_user.providers.user_item'] = new \Doyo\UserBundle\DataProvider\UserItemDataProvider(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')), 'App\\Entity\\User');
