<?php

/*
 * This file is part of the DoyoUserBundle project.
 *
 * (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'http_exception_listener' shared service.

include_once $this->targetDirs[4].'/vendor/symfony/http-kernel/EventListener/ExceptionListener.php';

return $this->privates['http_exception_listener'] = new \Symfony\Component\HttpKernel\EventListener\ExceptionListener(null, null, true, 'UTF-8', null);
