<?php

/*
 * This file is part of the DoyoUserBundle project.
 *
 * (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'test.client.history' service.

include_once $this->targetDirs[4].'/vendor/symfony/browser-kit/History.php';

$this->factories['service_container']['test.client.history'] = function () {
    return new \Symfony\Component\BrowserKit\History();
};

return $this->factories['service_container']['test.client.history']();
