<?php

/*
 * This file is part of the DoyoUserBundle project.
 *
 * (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'test.client' service.

include_once $this->targetDirs[4].'/vendor/symfony/browser-kit/Client.php';
include_once $this->targetDirs[4].'/vendor/symfony/http-kernel/Client.php';
include_once $this->targetDirs[4].'/vendor/symfony/framework-bundle/Client.php';
include_once $this->targetDirs[4].'/vendor/symfony/browser-kit/History.php';
include_once $this->targetDirs[4].'/vendor/symfony/browser-kit/CookieJar.php';

$this->factories['test.client'] = function () {
    return new \Symfony\Bundle\FrameworkBundle\Client(($this->services['kernel'] ?? $this->get('kernel', 1)), [], (new \Symfony\Component\BrowserKit\History()), (new \Symfony\Component\BrowserKit\CookieJar()));
};

return $this->factories['test.client']();
