<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.tUmnHqV' shared service.

return $this->privates['.service_locator.tUmnHqV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'user' => ['privates', '.errored..service_locator.tUmnHqV.Doyo\\UserBundle\\Model\\UserInterface', NULL, 'Cannot autowire service ".service_locator.tUmnHqV": it references interface "Doyo\\UserBundle\\Model\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
]);
