<?php

/*
 * This file is part of the DoyoUserBundle project.
 *
 * (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.tUmnHqV' shared service.

return $this->privates['.service_locator.tUmnHqV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'user' => ['privates', '.errored..service_locator.tUmnHqV.Doyo\\UserBundle\\Model\\UserInterface', null, 'Cannot autowire service ".service_locator.tUmnHqV": it references interface "Doyo\\UserBundle\\Model\\UserInterface" but no such service exists. Did you create a class that implements this interface?'],
]);
