<?php

/*
 * This file is part of the DoyoUserBundle project.
 *
 * (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'api_platform.doctrine.orm.default.item_data_provider' shared service.

include_once $this->targetDirs[4].'/vendor/api-platform/core/src/DataProvider/DenormalizedIdentifiersAwareItemDataProviderInterface.php';
include_once $this->targetDirs[4].'/vendor/api-platform/core/src/DataProvider/RestrictedDataProviderInterface.php';
include_once $this->targetDirs[4].'/vendor/api-platform/core/src/Bridge/Doctrine/Common/Util/IdentifierManagerTrait.php';
include_once $this->targetDirs[4].'/vendor/api-platform/core/src/Bridge/Doctrine/Orm/ItemDataProvider.php';

return $this->privates['api_platform.doctrine.orm.default.item_data_provider'] = new \ApiPlatform\Core\Bridge\Doctrine\Orm\ItemDataProvider(($this->services['doctrine'] ?? $this->getDoctrineService()), ($this->privates['api_platform.metadata.property.name_collection_factory.cached'] ?? $this->getApiPlatform_Metadata_Property_NameCollectionFactory_CachedService()), ($this->privates['api_platform.metadata.property.metadata_factory.cached'] ?? $this->getApiPlatform_Metadata_Property_MetadataFactory_CachedService()), new RewindableGenerator(function () {
    yield 0 => ($this->privates['api_platform.doctrine.orm.query_extension.eager_loading'] ?? $this->load('getApiPlatform_Doctrine_Orm_QueryExtension_EagerLoadingService.php'));
}, 1));
