<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.doyo_user.command.generate_jwt_keys' shared autowired service.

include_once $this->targetDirs[4].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[4].'/src/Command/GenerateJWTKeyCommand.php';

$this->services['console.command.public_alias.doyo_user.command.generate_jwt_keys'] = $instance = new \Doyo\UserBundle\Command\GenerateJWTKeyCommand();

$instance->setPath($this->getEnv('resolve:JWT_PUBLIC_KEY'), $this->getEnv('resolve:JWT_SECRET_KEY'), $this->getEnv('resolve:JWT_PASSPHRASE'));

return $instance;
