<?php

/*
 * This file is part of the DoyoUserBundle project.
 *
 * (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.doyo_user.command.generate_jwt_keys' shared autowired service.

include_once $this->targetDirs[4].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[4].'/src/Command/GenerateJWTKeyCommand.php';

$this->services['console.command.public_alias.doyo_user.command.generate_jwt_keys'] = $instance = new \Doyo\UserBundle\Command\GenerateJWTKeyCommand();

$instance->setPath($this->getEnv('resolve:JWT_PUBLIC_KEY'), $this->getEnv('resolve:JWT_SECRET_KEY'), $this->getEnv('resolve:JWT_PASSPHRASE'));

return $instance;
