<?php

/*
 * This file is part of the DoyoUserBundle project.
 *
 * (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fragment.renderer.inline' shared service.

include_once $this->targetDirs[4].'/vendor/symfony/http-kernel/Fragment/FragmentRendererInterface.php';
include_once $this->targetDirs[4].'/vendor/symfony/http-kernel/Fragment/RoutableFragmentRenderer.php';
include_once $this->targetDirs[4].'/vendor/symfony/http-kernel/Fragment/InlineFragmentRenderer.php';

$this->privates['fragment.renderer.inline'] = $instance = new \Symfony\Component\HttpKernel\Fragment\InlineFragmentRenderer(($this->services['http_kernel'] ?? $this->getHttpKernelService()), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));

$instance->setFragmentPath('/_fragment');

return $instance;
