<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Doyo\UserBundle\Controller\ResetPasswordController' shared autowired service.

include_once $this->targetDirs[4].'/src/Controller/ResetPasswordController.php';

return $this->services['Doyo\\UserBundle\\Controller\\ResetPasswordController'] = new \Doyo\UserBundle\Controller\ResetPasswordController();
