<?php

/*
 * This file is part of the DoyoUserBundle project.
 *
 * (c) Anthonius Munthi <me@itstoni.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.tUmnHqV.Doyo\UserBundle\Model\UserInterface' shared service.

include_once $this->targetDirs[4].'/vendor/symfony/security-core/User/UserInterface.php';
include_once $this->targetDirs[4].'/src/Model/UserInterface.php';

return $this->privates['.errored..service_locator.tUmnHqV.Doyo\\UserBundle\\Model\\UserInterface'] = new \Doyo\UserBundle\Model\UserInterface();
