<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.tUmnHqV.Doyo\UserBundle\Model\UserInterface' shared service.

include_once $this->targetDirs[4].'/vendor/symfony/security-core/User/UserInterface.php';
include_once $this->targetDirs[4].'/src/Model/UserInterface.php';

return $this->privates['.errored..service_locator.tUmnHqV.Doyo\\UserBundle\\Model\\UserInterface'] = new \Doyo\UserBundle\Model\UserInterface();
